
//User Login Data Store
export const APP_SET_USER_DATA = 'APP_SET_USER_DATA';
export const START_LOADING = 'START_LOADING';
export const SET_META_DATA = "SET_META_DATA";

export const SET_SAFE_AREA_INTENT = 'SET_SAFE_AREA_INTENT';
export const SET_SAFE_AREA_INTENT_CHAT = 'SET_SAFE_AREA_INTENT_CHAT';
export const SET_SAFE_AREA_INTENT_X = 'SET_SAFE_AREA_INTENT_X';
export const RESET_STORE = "RESET_STORE";
export const KEYBOARD_HEIGHT = "KEYBOARD_HEIGHT";
export const APP_LANGUAGE = "APP_LANGUAGE";
export const IS_GOOGLEAUT = "IS_GOOGLEAUT";

export const HOME_FAV_ARR = "HOME_FAV_ARR";
export const HOME_MOSTTRADE_ARR = "HOME_MOSTTRADE_ARR";
export const HOME_GAINERS_ARR = "HOME_GAINERS_ARR";
export const HOME_LOSERS_ARR = "HOME_LOSERS_ARR";

//POPUP
export const SHOW_ADDRESS_PICKER_POPUP = "SHOW_ADDRESS_PICKER_POPUP";

